config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home2'
  # root 'static_pages#particle_test'

  get 'home', to: 'static_pages#home3', as: 'home'

  get 'about_me', to: 'static_pages#about_me', as: 'about_me'

  get 'code_portfolio', to: 'static_pages#code_portfolio', as: 'code_portfolio'

  get 'resume', to: 'static_pages#resume', as: 'resume'

  get 'resume_open', to: 'static_pages#resume_open'

  get 'resume_download', to: 'static_pages#resume_download'

  get 'research', to: 'static_pages#research', as: 'research'

  get 'publications', to: 'static_pages#publications', as: 'publications'

  get 'awards', to: 'static_pages#awards', as: 'awards'

  get 'get_in_touch', to: 'static_pages#get_in_touch', as: 'get_in_touch'

  post 'get_in_touch', to: 'static_pages#email'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coming.rb
class Coming < ApplicationRecord
end

app/models/leaving.rb
class Leaving < ApplicationRecord
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController #The < sign indicates inheritance from ApplicationController

  def home
    @pictures = Picture.all
    @coming = Coming.all
    @leaving = Leaving.all
  end

  def about_me
  end

  def code_portfolio
    @projects = Project.all
  end

  def resume_open
    send_file "#{Rails.root}/app/assets/files/ElijahSpiroResume.pdf", type: 'application/pdf', disposition: 'inline'
  end

  def resume_download
    send_file "#{Rails.root}/app/assets/files/ElijahSpiroResume.pdf"
  end

  def research
  end

  def publications
  end

  def awards
  end

  def get_in_touch
  end

  def email
    ContactMailer.email_me(params[:name], params[:email], params[:text]).deliver
    redirect_to(root_path)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  #Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "Elijah Spiro"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar_global">
  <header class="navbar navbar-fixed-top navbar-inverse">
    <!--<div class="container">-->
      <div class="navbar-icons">
        <%= link_to image_tag("facebook_logo.png", class: :facebook_icon, alt: "Facebook"), "https://www.facebook.com/Elijah.Spiro", target: :_blank %>
        <%= link_to image_tag("github_logo.png", class: :github_icon, alt: "GitHub"), "https://github.com/ElijahAndNova", target: :_blank %>
        <%= link_to image_tag("link_logo.png", class: :link_icon, alt: "LinkdIn"), "https://www.linkedin.com/in/elijah-spiro-009526109/", target: :_blank %>
        <%= link_to image_tag("NASA_logo.png", class: :NASA_icon, alt: "NASA"), "https://www.nasa.gov/education/intern/feature/elijah-spiro-getting-by-with-a-little-help-from-a-friend", target: :_blank %>
      </div>
      <!--<nav>-->
      <ul class="nav navbar-nav navbar-right navbar-buttons">
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "About Me", about_me_path %></li>
        <li><%= link_to "Code Portfolio", code_portfolio_path %></li>
        <li><%= link_to "Resumé", resume_path%></li>
        <li><%= link_to "Research", research_path %></li>
        <li><%= link_to "Publications", publications_path %></li>
        <!--<li><%= link_to "Awards", awards_path %></li>-->
        <li><%= link_to "Get in Touch", get_in_touch_path %></li>
      </ul>
      <!--</nav>-->
    <!--</div>-->
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!--xmlns="http://www.w3.org/1999/xhtml"-->
<!--prefix="og: http://ogp.me/ns#">-->
<head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--<meta property="og:image" content="http://www.elijahspiro.com/assets/me6-34b1e28731f051e88f1d34246e30550de536a670a83d348ac2d305df527f0162.jpg">-->
    <!--<meta property="og:url" content="http://www.elijahspiro.com/assets/me6-34b1e28731f051e88f1d34246e30550de536a670a83d348ac2d305df527f0162.jpg">-->
    <!--<meta property="og:description" content="Learn about me and my work.">-->
    <!--<meta property="og:type" content="photo">-->
    </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="particles-json" data-particles="<%= asset_path('particles.json') %>">
      <%= yield %>
      <!--<%= render 'layouts/footer' %>-->
    </div>

    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-104863911-1']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>

  </body>

</html>

app/views/static_pages/about.html.erb
<% #provide(:title, "About") %>
<h1>About</h1>
<p>
  Elijah Spiro is building his first Ruby website.
</p>
<div class="panel">
  <div class="panel-heading">
    SUUUUUUUP
  </div>
  <div class="panel-body">
    HUOHDOIHDOIUHDOUDHOUDHOUDODOHDO
  </div>
</div>

app/views/static_pages/about_me.html.erb
<%= javascript_include_tag 'about', 'data-turbolinks-track'=> 'reload' %>

<div class="global">
  <div class="about-panels">
    <div class="row">
      <div class="panel-about">
        <%= image_tag("me6.jpg", class: :pic_of_me_5, alt: "#") %>
      </div>
      <div class="panel-about2">
        <h4><div class="title">About Me</div></h4>
        <br/>
        <div class="non-center">
          <div class="p1">
            &nbsp; &nbsp; &nbsp; &nbsp;I'm a rising senior studying computer science and astronomy
            at Amherst College, in Massachusetts. I'm the captain of my school's varsity swim team, where I hold multiple
            school records and have qualified for the NCAA championship meet both individually and as a part of relay teams.
            I've completed multiple internships with NASA, and I have participated in astrophysics research projects at
            Stanford University.
          </div>
          <br/>
          <br/>
          <div class="p2">
            &nbsp; &nbsp; &nbsp; &nbsp; I'm accompanied at school and work by my Diabetic Alert Service Dog, Nova. He's capable
            of smelling and reacting to the hormone that my body produces when my blood sugar drops or spikes quickly. He's saved
            my life on numerous occasions, and he is the first service animal to ever work at Kennedy Space Center-- he was even
            awarded a government badge.
          </div>
          <br/>
          <br/>
          <div class="p3">
            &nbsp; &nbsp; &nbsp; &nbsp;I believe that humanity has the potential to accomplish extraordinary feats, and I strive
            every day to be a part of that movement. Though my aspirations to become an astronaut were halted by a diabetes diagnosis,
            I refuse to let that define my contributions to America's space program. I write code for the Space Launch System,
            and I will help to put humans on Mars.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="home_button">
  <%= link_to "Home", root_path, class: "btn btn-lg texty"%>
</div>

<div class="mobile">
  <div class="about-panels">
    <div class="row">
      <div class="panel-about">
        <%= image_tag("me6.jpg", class: :pic_of_me_5, alt: "#") %>
      </div>
      <div class="panel-about2">
        <h4><div class="title">About Me</div></h4>
        <br/>
        <div class="non-center">
          <div class="p1">
            &nbsp; &nbsp; &nbsp; &nbsp;I'm a rising senior studying computer science and astronomy
            at Amherst College, in Massachusetts. I'm the captain of my school's varsity swim team, where I hold multiple
            school records and have qualified for the NCAA championship meet both individually and as a part of relay teams.
            I've completed multiple internships with NASA, and I have participated in astrophysics research projects at
            Stanford University.
          </div>
          <br/>
          <br/>
          <div class="p2">
            &nbsp; &nbsp; &nbsp; &nbsp; I'm accompanied at school and work by my Diabetic Alert Service Dog, Nova. He's capable
            of smelling and reacting to the hormone that my body produces when my blood sugar drops or spikes quickly. He's saved
            my life on numerous occasions, and he is the first service animal to ever work at Kennedy Space Center-- he was even
            awarded a government badge.
          </div>
          <br/>
          <br/>
          <div class="p3">
            &nbsp; &nbsp; &nbsp; &nbsp;I believe that humanity has the potential to accomplish extraordinary feats, and I strive
            every day to be a part of that movement. Though my aspirations to become an astronaut were halted by a diabetes diagnosis,
            I refuse to let that define my contributions to America's space program. I write code for the Space Launch System,
            and I will help to put humans on Mars.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/awards.html.erb
<%= javascript_include_tag 'awards', 'data-turbolinks-track'=> 'reload' %>

<div class="awards-panels">
  <div class="row">
    <div class="panel-awards">
      <%= image_tag("award1.jpg", class: :pic_of_award, alt: "#") %>
    </div>
    <!--<div class="panel-awards2">-->
    <!--</div>-->
  </div>
</div>

app/views/static_pages/code_portfolio.html.erb
<%= javascript_include_tag 'portfolio', 'data-turbolinks-track'=> 'reload' %>

<% #provide(:title, "Code Portfolio") %>

<div class="home_button">
  <%= link_to "Home", root_path, class: "btn btn-lg texty"%>
</div>


<div class="global">
  <div class="portfolio-panels">

    <%= image_tag("up_arrow.png", class:"arrow-up") %>

    <div class="panel-codeblock">
      <% @projects.each_with_index do |project, i| %>
          <div class="row project-panel" id="row_<%=i+1%>">
            <div class="col-xs-7 project_title", style="display:inline">
              <%= project.title %>
            </div>
            <div class="col-xs-7 project_description">
              <%= project.description.html_safe %>
            </div>
            <div class="col-xs-5">
              <%= image_tag(project.image_filepath) %>
            </div>
          </div>
      <% end %>
    </div>

    <%= image_tag("down_arrow.png", class:"arrow-down") %>

  </div>
</div>

<div class="mobile">

  <div class="portfolio-panels">

    <div class="proj1">
      <div class="proj_title">
        3D Engine - Built From Scratch
      </div>
      <%= image_tag("comet.png", class:"proj_pic") %>
      <div class="proj_description">
        &nbsp;&nbsp;&nbsp;&nbsp; I began developing this engine almost a year ago. This powerful work-in-progress 3D engine was written from scratch in Java, using only OpenGL.
        I plan to eventually release this project as a free download. The engine supports realistic physics, .obj model parsing, animation, particle effects,
        skyboxes, fog clipping, procedurally generated terrain, rippling water, and more.
        <br> <br>
        &nbsp;&nbsp;&nbsp;&nbsp; Upon release, I envision a program that allows the player to vary some settings that effect terrain generation, and explore the
        resulting world. The world will be populated with randomized alien scuttlers, flowing volcanoes, and deep oceans. The player can make use of the jetpack attached
        to their astronaut to fly around.
        <br> <br>
        &nbsp;&nbsp;&nbsp;&nbsp; And there are many more features to come! Stay tuned for updates and progress videos, as well as a download link.
        Soon, I will be devoting a whole page on my site to this project.
      </div>
    </div>

    <div class="proj2">
      <div class="proj_title">
        Artificial Intelligence Stock Picker
      </div>
      <%= image_tag("moneymoose.jpg", class:"proj_pic") %>
      <div class="proj_description">
        &nbsp;&nbsp;&nbsp;&nbsp; I wrote this program to analyze patterns on the American stock market and predict which stocks
        will rise or fall in price the next day, using a machine learning technique called boosting.
        <br> <br>
        &nbsp;&nbsp;&nbsp;&nbsp; The code is designed to be run once every day, after the stock market has closed. The user loads in a learning model, which
        dictates which parameters to examine and weigh.
        <br> <br>
        &nbsp;&nbsp;&nbsp;&nbsp; When thse code runs, it uses Google Finance API to deploy a webcrawler. This crawler scours information on the stocks from the
        S&P 500 and saves it to a log file marked with the day's timestamp. The parameters examined change based on the learning model used.
        <br> <br>
        &nbsp;&nbsp;&nbsp;&nbsp; In addition to obtaining the new day's information, the program examines whether its predictions from the previous day were correct.
        If the prediction for a given stock was incorrect, the program adjusts how heavily the given parameters are weighted in its prediction
        for the following day. The more consecutive days the program runs, the more accurate it will become.
      </div>
    </div>

    <div class="proj3">
      <div class="proj_title">
        SkyBit: 'Siri' for the Computer
      </div>
      <%= image_tag("skybit.png", class:"proj_pic") %>
      <div class="proj_description">
        &nbsp;&nbsp;&nbsp;&nbsp; This program began as a computer companion, designed to run in the background
        until it was needed; a combination of keyboard key presses would bring the console to the forefront of the user's screen, where they could
        enter a wide range of commands.
        <br> <br>
        &nbsp;&nbsp;&nbsp;&nbsp; As my astronomy research continued, I needed to write code that produced visual output; rather than starting from scratch,
        I merged the two projects. My computer companion gained the functionality to run complex simulations and display the result
        in its already fleshed-out system of display frames. SkyBit quickly became a tool to my research, with added functionality on the side.
        <br> <br>
        &nbsp;&nbsp;&nbsp;&nbsp; SkyBit's dynamic display provides real time information about your computer. Depending on the colors
        smoldering in the background and the ebb and flow of the pattern shown, the user could use SkyBit to easily track statistics such
        as computer memory being used in simulations and bits of data generated per second (FITS image files are huge).
        In addition to helping manage memory, SkyBit makes it easy to run specialized web searches, check the local weather,
        ping your email, and more.
      </div>
    </div>

    <div class="proj4">
      <div class="proj_title">
        Exoplanet Research PyKLIP Wrapper
      </div>
      <%= image_tag("pyklip.png", class:"proj_pic") %>
      <div class="proj_description">
        &nbsp;&nbsp;&nbsp;&nbsp; My primary field of research is in exoplanet direct imaging. One of the final steps in reducing data
        using this technique involves executing principal component analysis to sort out starlight from planetary light. To do this,
        we use <a target='_blank', href='https://bitbucket.org/pyKLIP/pyklip'>PyKLIP</a>, a PCA tool written by
        <a target='_blank', href='http://w.astro.berkeley.edu/~jwang/'>Jason Wang</a>.
        <br> <br>
        &nbsp;&nbsp;&nbsp;&nbsp; PyKLIP has several parameters that can be tweaked to change the result; every data set has different optimal parameter
        settings. To mitigate this confusion, I created a GUI that sets up an automated parameter space search on a given data set.
        <br> <br>
        &nbsp;&nbsp;&nbsp;&nbsp; This program makes it easy to set up and run several hundred PyKLIP processes, each of which can take hours to run. I wrote
        auxiliary helper code to analyze the output of the PyKLIP algorithm and evaluate its 'goodness' through signal to noise ratio mapping.
        The end result is a 3-dimensional data cube which reveals the optimal parameter combination for a data set.
        <br> <br>
        &nbsp;&nbsp;&nbsp;&nbsp; This project was written in Python and Java, and is tied together with a Bash script.
      </div>
    </div>

    <div class="proj5">
      <div class="proj_title">
        8-bit Computer with Assembly OS
      </div>
      <%= image_tag("8bit.jpg", class:"proj_pic") %>
      <div class="proj_description">
        &nbsp;&nbsp;&nbsp;&nbsp; Excuse the mess! I was part of a small team of students tasked with constructing an 8-bit computer from scratch. The first phase
        of the project involved building the physical components out of spools of wire, bread board, and logic gates. We developed a build strategy
        that included each individual piece of the computer system, from the CPU to the data caches and registers.
        <br> <br>
        &nbsp;&nbsp;&nbsp;&nbsp; After weeks of work, we had a working computer that accepted commands in the form of 8 unique opcodes. The next step
        was to write an operating system in Assembly that could run on our computer and utilise all 8 opcodes to perform a task. Some examples
        of the opcodes that we built were ADD, SUBTRACT, MULTIPLY, SAVE, and LOAD. Finally, we loaded our assembly code on to a programmable microcontroller.
        Days of painstaking troubleshooting later, we had all 8 opcodes working with our code.
        <br> <br>
        &nbsp;&nbsp;&nbsp;&nbsp; This project taught me a lot about the inner mechanics of the modern computer, and gave me more respect for system engineers.
      </div>
    </div>

  </div>

</div>

app/views/static_pages/contact.html.erb
<% #provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact Elijah at:
  elijah.r.spiro@nasa.gov
</p>

app/views/static_pages/get_in_touch.html.erb
<%= javascript_include_tag 'get_in_touch', 'data-turbolinks-track'=> 'reload' %>

<div class="global">
  <div class="row">
    <div class="panel-get-in-touch">
      <div class="panel-get-in-touch2">
        <h4><div class="get-in-touch-title">Contact Me:</div></h4>
        <br/>
        <h4><div class="get-in-touch-title2">espiro18@amherst.edu</div></h4>
      </div>

      <div class="panel-get-in-touch3">
        <div class="non-center">
          <div class="para1">
            <h4><center>Available Services</center></h4>
            <br>
            <ul>
              <li>Software Development</li>
              <li>Web Design</li>
              <li>App Creation</li>
              <li>Systems Engineering</li>
              <li>Artificial Intelligence Programming</li>
              <li>3D Modeling</li>
              <li>Algorithm Analysis</li>
              <li>Problem Solving</li>
            </ul>
            <!--&nbsp; &nbsp; &nbsp; &nbsp; I-->
          </div>
        </div>
      </div>

      <div class="panel-get-in-touch4">
        <div class="non-center">
          <div class="para1">
            <h4><center>Languages + Frameworks</center></h4>
            <br>
            <ul>
              <li>Java</li>
              <li>C++, Objective C</li>
              <li>Python</li>
              <li>Ruby, Javascript, HTML, CSS</li>
              <li>Bash Scripting</li>
              <li>Ruby on Rails, Robot Framework, SikuliX, OpenGL, Matlab, Version Control Software (Git, AccuRev)  </li>
            </ul>
            <!--&nbsp; &nbsp; &nbsp; &nbsp; I-->
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

<div class="home_button">
  <%= link_to "Home", root_path, class: "btn btn-lg texty"%>
</div>

<div class="mobile">
  <div class="row">
    <div class="panel-get-in-touch">
      <div class="panel-get-in-touch2">
        <h4><div class="get-in-touch-title">Contact Me:</div></h4>
        <br/>
        <h4><div class="get-in-touch-title2">espiro18@amherst.edu</div></h4>
      </div>

      <div class="panel-get-in-touch3">
        <div class="non-center">
          <div class="para1">
            <h4><center>Available Services</center></h4>
            <br>
            <ul>
              <li>Software Development</li>
              <li>Web Design</li>
              <li>App Creation</li>
              <li>Systems Engineering</li>
              <li>Artificial Intelligence Programming</li>
              <li>3D Modeling</li>
              <li>Algorithm Analysis</li>
              <li>Problem Solving</li>
            </ul>
            <!--&nbsp; &nbsp; &nbsp; &nbsp; I-->
          </div>
        </div>
      </div>

      <div class="panel-get-in-touch4">
        <div class="non-center">
          <div class="para1">
            <h4><center>Languages + Frameworks</center></h4>
            <br>
            <ul>
              <li>Java</li>
              <li>C++, Objective C</li>
              <li>Python</li>
              <li>Ruby, Javascript, HTML, CSS</li>
              <li>Bash Scripting</li>
              <li>Ruby on Rails, Robot Framework, Sikuli, OpenGL, Matlab, Version Control Software (Git, AccuRev)  </li>
            </ul>
            <!--&nbsp; &nbsp; &nbsp; &nbsp; I-->
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/static_pages/help.html.erb
<% #provide(:title, "Help") %>
<h1>Help</h1>
<p>
  There's nothing that I can do to help you.
</p>

app/views/static_pages/old_home.html.erb
<%= javascript_include_tag 'old_home', 'data-turbolinks-track'=> 'reload' %>

<% #provide(:title, "Home") %>

<div class="all">
  <div class="center jumbotron">
    <%= image_tag("experimental.png", class: :name_icon, alt: "#") %>
  </div>
  <div class="ultimate">
    <div class="row">
      <h7>
        <div class="pedigrees">
          NASA Intern <i class="fa fa-space-shuttle"></i> Computer Scientist <i class="fa fa-space-shuttle"></i> Astronomer<i class="fa fa-space-shuttle"></i> Collegiate Swimmer <i class="fa fa-space-shuttle"></i>Service Dog Handler
        </div>
      </h7>
    </div>

    <!--<div class="row">-->
      <!--<div class="panel-custom0">-->
        <!--<%= link_to "About Me", about_me_path, class: "btn btn-lg btn-custom3" %>-->
        <!--<%= link_to "Code Portfolio", code_portfolio_path, class: "btn btn-lg btn-custom3" %>-->
        <!--<%= link_to "Resumé", resume_path, class: "btn btn-lg btn-custom3", target: :_blank %>-->
        <!--<%= link_to "Research", research_path, class: "btn btn-lg btn-custom3" %>-->
        <!--<%= link_to "Publications", publications_path, class: "btn btn-lg btn-custom3" %>-->
        <!--<%= link_to "Awards", awards_path, class: "btn btn-lg btn-custom3" %>-->
        <!--<%= link_to "Get in Touch", get_in_touch_path, class: "btn btn-lg btn-custom3" %>-->
      <!--</div>-->
    <!--</div>-->

    <div class="animate">
      <div class="row">
        <div class="col-md-1 scroll1">
          <div class="panel-custom1-old">
            <div class="panel-heading">
              <%= image_tag("me1.jpg", class: :pic_of_me_1, alt: "#") %>
            </div>
          </div>
        </div>

        <div class="col-md-1 scroll2">
          <div class="panel-custom2">
            <div class="panel-heading">
              <%= image_tag("me2.jpg", class: :pic_of_me_2, alt: "#") %>
            </div>
          </div>
        </div>

        <div class="col-md-1 scroll3">
          <div class="panel-custom3">
            <div class="panel-heading">
              <%= image_tag("me3.jpg", class: :pic_of_me_3, alt: "#") %>
            </div>
          </div>
        </div>

        <div class="col-md-1 scroll4">
          <div class="panel-custom4">
            <div class="panel-heading">
              <%= image_tag("me4.jpg", class: :pic_of_me_4, alt: "#") %>
            </div>
          </div>
        </div>

        <div class="col-md-1 scroll5">
          <div class="panel-custom5">
            <div class="panel-heading">
              <%= image_tag("new2.jpg", class: :pic_of_me_6, alt: "#") %>
            </div>
          </div>
        </div>

        <div class="col-md-1 scroll6">
          <div class="panel-custom6">
            <div class="panel-heading">
              <%= image_tag("new4.jpg", class: :pic_of_me_7, alt: "#") %>
            </div>
          </div>
        </div>

      </div>
        <!--<div class="col-md-4">-->
          <!--<div class="panel-custom00">-->
            <!--<div class="panel-text">-->
              <!--<h4>-->
                  <!--Welcome to my website!-->
              <!--</h4>-->
              <!--<p>-->
               <!--&emsp;&emsp; My name is Elijah. I'm currently finishing up school at Amherst College, with an intended double major in Computer Science and Astronomy.-->
              <!--</p>-->
              <!--<p>-->
                <!--&emsp;&emsp;Please take a look around, and be sure to check out my projects, publications, and resume using the buttons above. Feel free to contact me with any questions or concerns at:-->
              <!--</p>-->

              <!--<p>-->
                <!--espiro18@amherst.edu-->
              <!--</p>-->
            <!--</div>-->
          <!--</div>-->
        <!--</div>-->
    </div>
  </div>
</div>

app/views/static_pages/resume.html.erb
<%= javascript_include_tag 'resume', 'data-turbolinks-track'=> 'reload' %>

<div class="global">
  <div class="panel-resume0">
    <div class="panel-resume1">
      <div id="toFade">
        <div class="h2">Resume</div>
        <div class="row">
          <%= link_to "Open", resume_open_path, class: "btn btn-lg btn-resume", target: :_blank %>
          <%= link_to "Download", resume_download_path, class: "btn btn-lg btn-resume"%>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="home_button">
  <%= link_to "Home", root_path, class: "btn btn-lg texty"%>
</div>

<div class="mobile">
  <div class="panel-resume0">
    <div class="panel-resume1">
      <div id="toFade">
        <div class="h2">Resume</div>
        <div class="row">
          <%= link_to "Open", resume_open_path, class: "btn btn-lg btn-resume", target: :_blank %>
        </div>
      </div>
    </div>
  </div>
</div>